### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm.cpp#41]
Ranked by priority

- [] handle s(tep) with operator+/-(=)
- [] support all Params (starting with file descriptor output)
- [] fix potential range update bug
- [] anon namespaces
- [] thread safety
- [] coverage reporting
- [] release 0.0.1-py4.8.4 (includes based-on-tqdm.py version)
- [] reverse iterators

*taken from /dev brancg*
